name: Update AL-Go System Files

on:
  workflow_dispatch:
    inputs:
      directCommit:
        description: Direct COMMIT (Y/N)
        required: false
        default: 'N'

defaults:
  run:
    shell: PowerShell

jobs:
  update:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Read settings
        uses: PooyaKharamesh/AL-Go-Actions/ReadSettings@main
        with:
          get: KeyVaultName,GhTokenWorkflowSecretName,TemplateUrl,TemplateBranch

      - name: Read secrets
        uses: PooyaKharamesh/AL-Go-Actions/ReadSecrets@main
        env:
          secrets: ${{ toJson(secrets) }}
        with:
          settingsJson: ${{ env.Settings }}
          secrets: 'ghTokenWorkflow=${{ env.GHTOKENWORKFLOWSECRETNAME }}'

      - name: Update AL-Go system files
        uses: PooyaKharamesh/AL-Go-Actions/CheckForUpdates@main
        with:
          token: ${{ env.ghTokenWorkflow }}
          update: Y
          templateUrl: ${{ env.TemplateUrl }}
          templateBranch: ${{ env.TemplateBranch }}
          directCommit: ${{ github.event.inputs.directCommit }}
